copyright    = ""
dateFormat   = "2 January 2006"
description  = "Le Club Info est un club étudiant de l'INSA Toulouse qui a pour but de promouvoir l'informatique et les sciences du numérique auprès des étudiants de l'INSA Toulouse."
displayName  = "FR"
image        = "img/logo.png"
isoCode      = "fr"
languageCode = "fr"
languageName = "French"
rtl          = false
title        = "Club Info INSA Toulouse"
weight       = 1
[author]
  bio = ""
  headline = "INSA Toulouse"
  image = "img/logo.png"
  links = [
    {email = "mailto:club.info@amicale-insat.fr"},
    {discord = "https://discord.gg/9G8cWyK"},
    {facebook = "https://facebook.com/ClubInfoINSAT"},
    {github = "https://github.com/ClubInfoInsaT/"},
    {instagram = "https://www.instagram.com/clubinfoinsat/"},
    {linkedin = "https://linkedin.com/in/club-info-insa-toulouse"},
  ]
  name = "Club Info"
