# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
    name   = "Acceuil"
    url    = "/"
    weight = 10
# [[main]]
#     name    = "A Propos"
#     pageRef = "about"
#     weight  = 20
[[main]]
    name    = "Présentations"
    pageRef = "presentations"
    weight  = 30
[[main]]
    name    = "Nos Projets"
    pageRef = "projects"
    weight  = 40
[[main]]
    name    = "Parcours de formations"
    pageRef = "courses"
    weight  = 50

[[main]]
    name    = "SCE"
    pageRef = "sce"
    weight  = 51
[[main]]
    name   = "Cod'INSA"
    url    = "https://codinsa.org"
    weight = 52
[[main]]
    name   = "WikiEtud"
    url    = "https://wiki.etud.insa-toulouse.fr/"
    weight = 53

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
    name    = "Semaines Climat Energie"
    pageRef = "sce"
    weight  = 10
[[footer]]
    name   = "Cod'INSA"
    url    = "https://codinsa.org"
    weight = 20
[[footer]]
    name   = "WikiEtud"
    url    = "https://wiki.etud.insa-toulouse.fr/"
    weight = 30
