# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

autoSwitchAppearance = false
colorScheme          = "blowfish"
defaultAppearance    = "dark"     # valid options: light or dark

enableCodeCopy = true
enableSearch   = true

mainSections = ["projets"]
# robots = ""

disableImageOptimization = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC                 = true
# smartTOCHideUnfocusedChildren = true

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showAppearanceSwitcher = false
  showCopyright          = true
  showMenu               = true
  showScrollToTop        = true
  showThemeAttribution   = false

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  cardView             = true
  cardViewScreenWidth  = false
  layoutBackgroundBlur = false      # only used when layout equals background
  showMoreLink         = true
  showMoreLinkDest     = "/projets"
  showRecent           = true
  showRecentItems      = 5

[article]
  editAppendPath              = true
  editURL                     = "https://github.com/ClubInfoINSAT/site-club-info"
  heroStyle                   = "big"                                             # valid options: basic, big, background, thumbAndBackground
  invertPagination            = false
  layoutBackgroundBlur        = true                                              # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true                                              # only used when heroStyle equals background
  seriesOpened                = false
  showAuthor                  = true
  showBreadcrumbs             = true
  showDate                    = true
  showDateUpdated             = false
  showDraftLabel              = true
  showEdit                    = true
  showHeadingAnchors          = true
  showHero                    = true
  showLikes                   = false
  showPagination              = true
  showReadingTime             = true
  showTableOfContents         = true
  showViews                   = false
  # showRelatedContent = false
  # relatedContentLimit = 3
  sharingLinks = [
    "linkedin",
    "twitter",
    # "reddit",
    # "pinterest",
    "facebook",
    "email"
    # "whatsapp",
    # "telegram"
  ]
  showAuthorsBadges = true
  showSummary = true
  showTaxonomies = true
  showWordCount = true

[list]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  cardView                    = false
  cardViewScreenWidth         = false
  constrainItemsWidth         = false
  groupByYear                 = true
  layoutBackgroundBlur        = true  # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true  # only used when heroStyle equals background
  showBreadcrumbs             = false
  showCards                   = true
  showLikes                   = false
  showSummary                 = true
  showTableOfContents         = true
  showViews                   = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showHero      = false
  showTermCount = true
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  cardView            = false
  showBreadcrumbs     = false
  showLikes           = false
  showTableOfContents = false
  showViews           = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  cardView            = false
  cardViewScreenWidth = false
  groupByYear         = false
  showBreadcrumbs     = false
  showLikes           = false
  showTableOfContents = true
  showViews           = false
