# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters
autoSwitchAppearance = true
colorScheme          = "blowfish"
defaultAppearance    = "light"    # valid options: light or dark
disableImageZoom     = true
enableCodeCopy       = true
enableSearch         = true
# logo                 = "img/logo.png"
mainSections = ["home", "projects"]
# robots = ""
[footer]
  # showMenu = true
  showAppearanceSwitcher = true
  showCopyright          = true
  showScrollToTop        = true
  showThemeAttribution   = false
[homepage]
  cardView            = false
  cardViewScreenWidth = false
  # homepageImage       = "img/logo.png" # used in: hero, background and card
  layout       = "custom" # valid options: page, profile, hero, card, background, custom
  showMoreLink = true
  showMoreLinkDest = "/projects"
  showRecent       = true
  showRecentItems  = 5
[article]
  showDate = true
  #showViews = true
  #showLikes = true
  editAppendPath      = false
  editURL             = "https://github.com/ClubInfoINSAT/site-club-info/"
  heroStyle           = "background"                                       # valid options: basic, big, background
  invertPagination    = false
  seriesOpened        = false
  sharingLinks        = ["linkedin", "twitter", "email"]
  showAuthor          = true
  showAuthorsBadges   = true
  showBreadcrumbs     = true
  showDateUpdated     = false
  showDraftLabel      = true
  showEdit            = true
  showHeadingAnchors  = true
  showHero            = true
  showPagination      = true
  showReadingTime     = true
  showSummary         = true
  showTableOfContents = true
  showTaxonomies      = true
  showWordCount       = true
[list]
  cardView            = false
  cardViewScreenWidth = false
  groupByYear         = true
  showBreadcrumbs     = false
  showCards           = false
  showSummary         = true
  showTableOfContents = false
[sitemap]
  excludedKinds = []
[taxonomy]
  showTermCount = true